/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AccountPage` | `/AccountPage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Creators` | `/Creators`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/JoinRoom` | `/JoinRoom`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/WatchParty` | `/WatchParty`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/AccountPage` | `/AccountPage`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Creators` | `/Creators`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/JoinRoom` | `/JoinRoom`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/WatchParty` | `/WatchParty`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/AccountPage${`?${string}` | `#${string}` | ''}` | `/AccountPage${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Creators${`?${string}` | `#${string}` | ''}` | `/Creators${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/JoinRoom${`?${string}` | `#${string}` | ''}` | `/JoinRoom${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/WatchParty${`?${string}` | `#${string}` | ''}` | `/WatchParty${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AccountPage` | `/AccountPage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Creators` | `/Creators`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/JoinRoom` | `/JoinRoom`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/WatchParty` | `/WatchParty`; params?: Router.UnknownInputParams; };
    }
  }
}
