/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/FavoritesScreen` | `/FavoritesScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/MovieSwipeScreen` | `/MovieSwipeScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/VibeInputScreen` | `/VibeInputScreen`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/FavoritesScreen` | `/FavoritesScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/MovieSwipeScreen` | `/MovieSwipeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/VibeInputScreen` | `/VibeInputScreen`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/FavoritesScreen${`?${string}` | `#${string}` | ''}` | `/FavoritesScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/MovieSwipeScreen${`?${string}` | `#${string}` | ''}` | `/MovieSwipeScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/VibeInputScreen${`?${string}` | `#${string}` | ''}` | `/VibeInputScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/FavoritesScreen` | `/FavoritesScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/MovieSwipeScreen` | `/MovieSwipeScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/VibeInputScreen` | `/VibeInputScreen`; params?: Router.UnknownInputParams; };
    }
  }
}
